export const mockJobs = [
  {
    id: 1,
    title: 'Senior Product Designer',
    company: 'Northstar Studio',
    location: 'Austin, TX',
    description: 'Shape calm, intuitive experiences for teams building their next great product.',
    employment_type: 'full_time',
    workplace_type: 'hybrid',
    salary_min: 120000,
    salary_max: 148000,
    salary_currency: 'USD',
    created_at: new Date().toISOString(),
  },
  {
    id: 2,
    title: 'Frontend Engineer',
    company: 'Morrow Labs',
    location: 'Remote',
    description: 'Build thoughtful, high-quality interfaces used by creative teams around the world.',
    employment_type: 'full_time',
    workplace_type: 'remote',
    salary_min: 135000,
    salary_max: 170000,
    salary_currency: 'USD',
    created_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 3,
    title: 'Customer Success Lead',
    company: 'Goodwork',
    location: 'Chicago, IL',
    description: 'Help growing companies get more value from the way their teams work together.',
    employment_type: 'full_time',
    workplace_type: 'hybrid',
    salary_min: 95000,
    salary_max: 120000,
    salary_currency: 'USD',
    created_at: new Date(Date.now() - 129600000).toISOString(),
  },
  {
    id: 4,
    title: 'Brand Marketing Manager',
    company: 'Sunday Goods',
    location: 'New York, NY',
    description: 'Tell stories that make an emerging lifestyle brand impossible to forget.',
    employment_type: 'full_time',
    workplace_type: 'on_site',
    salary_min: 105000,
    salary_max: 132000,
    salary_currency: 'USD',
    created_at: new Date(Date.now() - 259200000).toISOString(),
  },
  {
    id: 5,
    title: 'Data Analyst',
    company: 'Fieldnote',
    location: 'Remote',
    description: 'Turn complex product and customer data into decisions that move the business.',
    employment_type: 'full_time',
    workplace_type: 'remote',
    salary_min: 90000,
    salary_max: 118000,
    salary_currency: 'USD',
    created_at: new Date(Date.now() - 345600000).toISOString(),
  },
  {
    id: 6,
    title: 'People Operations Partner',
    company: 'Canopy Health',
    location: 'Denver, CO',
    description: 'Create the systems and rituals that help a mission-driven team do its best work.',
    employment_type: 'full_time',
    workplace_type: 'hybrid',
    salary_min: 88000,
    salary_max: 110000,
    salary_currency: 'USD',
    created_at: new Date(Date.now() - 432000000).toISOString(),
  },
];
